POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "author": "Alberts",
    "url": "albert.com",
    "likes": 6
}

###
GET http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
